### ISSUE TITLE
Add information about YAPiC to DeepImageJ website

### ISSUE THREAD

**Issue by cmohl2013** [deepimagej/deepimagej#4]
Dear DeepimageJ developers,

we have just released the new YAPiC version, which is able to deploy trained models as DeepImageJ bundeled model now. 
I just would like to ask you if you want mention this on your webiste and also add a link the YAPiC website.

https://yapic.github.io/yapic/

I explain the use in this tutorial:
https://yapic.github.io/yapic/tutorial_deepimagej.html

Best
Christoph

**Comment by esgomezm** [comment]
sorry I've just seen this! Very nice tutorial

I embedded your tutorial into our web page: 

https://deepimagej.github.io/deepimagej/tutorials.html#YAPIC-tutorial

Is it ok for you?

**Comment by cmohl2013** [comment]
Hi @esgomezm 
thank you, looks great!
